Refactor using testify and upgrade go v1.22.7
pavel-v-chernykh/keystore-go pull request #53
Opened 2024-10-01 07:17 UTC by nitram509

Pavlo, as we wrote in the other issue about p12 support, 
I thought it's best to split the tasks. 
This is the full refactoring, so that `testify` lib is used in all tests.

Also, I did upgrade to Go 1.22.7 and this led to updates to golinter as well.
About the linter ... I spent quite some time fixing linter issues.
Therefore, you see more changes than necessary, because with Go 1.22, the linter went more "aggressive".

Any feedback is welcome.
Also, it would be great to get the 'hacktoberfest-approved' label ;)

2024-10-01 14:18 UTC, pavlo-v-chernykh commented
I’ve added the `hacktoberfest-accepted` label required by the participation rules. However, I couldn’t find any mention of the `hacktoberfest-approved` label on [Hacktoberfest Participation](https://hacktoberfest.com/participation). Please let me know what it is used for.

2024-10-01 15:30 UTC, pavlo-v-chernykh requested changes
Thank you for your contribution @nitram509 

I left several comments, please address them.

Also, please fix the next linter warnings as well:
```
WARN [config_reader] The configuration option `linters.gomnd.settings` is deprecated. Please use the options `linters.gomnd.checks`,`linters.gomnd.ignored-numbers`,`linters.gomnd.ignored-files`,`linters.gomnd.ignored-functions`.
WARN [lintersdb] The linter "exhaustivestruct" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
WARN [lintersdb] The linter "scopelint" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
WARN [lintersdb] The linter "golint" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
WARN [lintersdb] The linter "interfacer" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
WARN [lintersdb] The linter "maligned" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle
WARN [lintersdb] The name "goerr113" is deprecated. The linter has been renamed to: err113.
WARN The linter 'execinquery' is deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
WARN The linter 'gomnd' is deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd.
```

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		binary.BigEndian.PutUint16(buf, uint16(len(str))) //nolint:all
Same here about nolint

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on encoder.go
> +	if err := e.writeUint64(uint64(pke.CreationTime.UnixMilli())); err != nil { //nolint:all
Same here about nolint

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on encoder.go
> +	if err := e.writeUint64(uint64(tce.CreationTime.UnixMilli())); err != nil { //nolint:all
Same here about nolint

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on keystore.go
> +	if err := e.writeUint32(uint32(len(ks.m))); err != nil { //nolint:all
Same here about nolint

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on keystore.go
> +	actualDigest, err := d.readBytes(uint32(d.h.Size())) //nolint:all
Same here about nolint

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on keystore_test.go
> +	assert.Truef(t, reflect.DeepEqual(actualPKE.PrivateKey, decodedPK.Bytes),
Please consider using `assert.Equal` and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on keystore_test.go
> +	assert.True(t, reflect.DeepEqual(actualPKE.PrivateKey, decodedPK.Bytes), "unexpected private key")
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on keystore_test.go
> +	assert.True(t, reflect.DeepEqual(expectedAliases, actualAliases), "aliases must be equal")
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on keystore_test.go
> +	assert.True(t, reflect.DeepEqual(tce, tceGet), "private key entries not equal")
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		assert.Truef(t, reflect.DeepEqual(hash, tt.hash[:]), "invalid hash '%v' '%v'", hash, tt.hash)
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		assert.Truef(t, reflect.DeepEqual(hash, tt.hash[:]), "invalid hash '%v' '%v'", hash, tt.hash)
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		assert.Truef(t, reflect.DeepEqual(hash, tt.hash[:]), "invalid hash '%v' '%v'", hash, tt.hash)
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		assert.Truef(t, reflect.DeepEqual(bts, tt.bytes), "invalid bytes '%v' '%v'", bts, tt.bytes)
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		assert.Truef(t, reflect.DeepEqual(hash, tt.hash[:]), "invalid hash '%v' '%v'", hash, tt.hash)
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		assert.Truef(t, reflect.DeepEqual(err, tt.err), "invalid error '%v' '%v'", err, tt.err)
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		assert.Truef(t, reflect.DeepEqual(hash, tt.hash[:]), "invalid hash '%v' '%v'", hash, tt.hash)
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		assert.Truef(t, reflect.DeepEqual(err, tt.err), "invalid error '%v' '%v'", err, tt.err)
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		assert.Truef(t, reflect.DeepEqual(hash, tt.hash[:]), "invalid hash '%v' '%v'", hash, tt.hash)
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 15:30 UTC, pavlo-v-chernykh commented on decoder_test.go
> +		assert.Truef(t, reflect.DeepEqual(err, tt.err), "invalid error '%v' '%v'", err, tt.err)
Please consider using assert.Equal and put expected and actual arguments in a correct order.

2024-10-01 17:39 UTC, nitram509 commented
Thanks for your comprehensive review.

---

> Also, please fix the next linter warnings as well:
> WARN [config_reader] The configuration option `linters.gomnd.settings` is deprecated. Please use the options `linters.gomnd.checks`,`linters.gomnd.ignored-numbers`,`linters.gomnd.ignored-files`,`linters.gomnd.ignored-functions`.

Just FYI: tried already, that lead to other "warning", which felt like an odd chain.
Will try again.

2024-10-01 19:06 UTC, nitram509 commented on common_test.go
> +		assert.Truef(t, reflect.DeepEqual(output, tt.output), "convert password bytes '%v', '%v'", output, tt.output)
did switch to `.Equal(expected, actual)` as the documentation says.

2024-10-01 19:48 UTC, nitram509 commented
@pavlo-v-chernykh 
I did implement all your suggestions and got rid of the warnings.

2024-10-01 19:55 UTC, pavlo-v-chernykh commented
Great work on this PR, @nitram509 🎉

Merging now! 🚀

Thanks for your contribution!

2024-10-01 19:55 UTC, pavlo-v-chernykh approved these changes

2024-10-01 19:57 UTC, merged

2025-12-01 08:49 UTC, farazkhawaja commented
Any plans to upgrade to latest go? @pavlo-v-chernykh